Fix/32 regnrer le projet oofservice
Antonin-Artaud/Aled.OpenFoodFact pull request #6
Opened 2024-08-01 09:36 UTC by Antonin-Artaud

2024-08-01 21:17 UTC, KRXTCH requested changes

2024-08-01 21:17 UTC, KRXTCH commented on aspnet-core/src/Aled.OpenFoodFactService.Application.Contracts/OpenFoodFactServiceApplicationContractsModule.cs
> +    typeof(OpenFoodFactServiceDomainSharedModule),
jme demandais si certains imports étaient vraiment utiles vu qu'on s'en sert pas (pareil dans les autres fichiers) ?

2024-08-01 21:17 UTC, KRXTCH commented on aspnet-core/src/Aled.OpenFoodFactService.Application.Contracts/OpenFoodFactServiceDtoExtensions.cs
> +}
t'as ajouté des espaces à grave de fichiers, jte laisse le choix de corriger ou non en checkant les changements ca se vois vite sinon c'est pas très grave

2024-08-01 21:17 UTC, KRXTCH commented on aspnet-core/src/Aled.OpenFoodFactService.DbMigrator/appsettings.json
> +        "RootUrl": "https://localhost:44387"
tu l'as enlever du .env ?

2024-08-01 21:17 UTC, KRXTCH commented on aspnet-core/src/Aled.OpenFoodFactService.HttpApi.Host/Properties/launchSettings.json
> +      "applicationUrl": "https://192.168.1.95:44387",
à rajouter dans le .env non ?

2024-08-01 21:17 UTC, KRXTCH commented on aspnet-core/src/Aled.OpenFoodFactService.MongoDB/MongoDb/OpenFoodFactServiceMongoDbModule.cs
> +            //options.AddRepository<Product, IRepository<Product, Guid>>();
commentaire à supp

2024-08-01 21:49 UTC, Antonin-Artaud commented on aspnet-core/src/Aled.OpenFoodFactService.Application.Contracts/OpenFoodFactServiceDtoExtensions.cs
> +}
j'vais le corriger yes

2024-08-01 21:49 UTC, Antonin-Artaud commented on aspnet-core/src/Aled.OpenFoodFactService.DbMigrator/appsettings.json
> +        "RootUrl": "https://localhost:44387"
j'vais refaire une passe sur le .env

2024-08-01 21:50 UTC, Antonin-Artaud commented on aspnet-core/src/Aled.OpenFoodFactService.HttpApi.Host/Properties/launchSettings.json
> +      "applicationUrl": "https://192.168.1.95:44387",
j'vais le laisser à false par défaut je pense comme pour Aled

2024-08-01 21:50 UTC, Antonin-Artaud commented on aspnet-core/src/Aled.OpenFoodFactService.MongoDB/MongoDb/OpenFoodFactServiceMongoDbModule.cs
> +            //options.AddRepository<Product, IRepository<Product, Guid>>();
yes

2024-08-02 05:56 UTC, KRXTCH commented on aspnet-core/src/Aled.OpenFoodFactService.HttpApi.Host/Properties/launchSettings.json
> +      "applicationUrl": "https://192.168.1.95:44387",
je parlais plus de l'applicationUrl mdrrrr

2024-08-02 12:15 UTC, Antonin-Artaud commented on aspnet-core/src/Aled.OpenFoodFactService.Application.Contracts/OpenFoodFactServiceApplicationContractsModule.cs
> +    typeof(OpenFoodFactServiceDomainSharedModule),
je vais investiguer sur ça

2024-08-02 12:15 UTC, merged